title: "@blockarchitech"
email: hello@blockarchitech.com
description: > # this means to ignore newlines until "baseurl:"
  stonks
baseurl: "" # the subpath of your site, e.g. /blog
tagline: stonks
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github:
  username:  blockarchitech
lang: en_US
#limit_posts: 10

# Theme settings
minima_dude:
  date_format: "%-d %b %Y"
  whackwhack: false    # Splits site title into spaces, adds // to the beginning and colours the words so the first half are white and the second half are red

dns_prefetch:
  - d33wubrfki0l68.cloudfront.net
  - www.google-analytics.com

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [test, development]
  profile: false
  startings: [html, body]

# Build settings
markdown: kramdown
remote_theme: lildude/minima-dude
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
